package com.lege.android.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.lege.android.base.db.AlarmUser;
import com.lege.android.base.db.ArticleHistoryBean;
import com.lege.android.base.db.AudioRecordUser;
import com.lege.android.base.db.CollectionUser;
import com.lege.android.base.db.EmailMessageUser;
import com.lege.android.base.db.EmailUser;
import com.lege.android.base.db.GlobalClockUser;
import com.lege.android.base.db.MessageUser;
import com.lege.android.base.db.MissedCallRecordUser;
import com.lege.android.base.db.NewRemindUser;
import com.lege.android.base.db.NewsUser;
import com.lege.android.base.db.NoticeUser;
import com.lege.android.base.db.PlanUser;
import com.lege.android.base.db.RecentlyPlayedUser;
import com.lege.android.base.db.ReminderUser;
import com.lege.android.base.db.ScheduleUser;
import com.lege.android.base.db.TaskBean;
import com.lege.android.base.db.TipsHistoryBean;
import com.lege.android.base.db.User;
import com.lege.android.base.db.WallpaperUser;
import com.lege.android.base.db.WeatherUser;

import com.lege.android.db.AlarmUserDao;
import com.lege.android.db.ArticleHistoryBeanDao;
import com.lege.android.db.AudioRecordUserDao;
import com.lege.android.db.CollectionUserDao;
import com.lege.android.db.EmailMessageUserDao;
import com.lege.android.db.EmailUserDao;
import com.lege.android.db.GlobalClockUserDao;
import com.lege.android.db.MessageUserDao;
import com.lege.android.db.MissedCallRecordUserDao;
import com.lege.android.db.NewRemindUserDao;
import com.lege.android.db.NewsUserDao;
import com.lege.android.db.NoticeUserDao;
import com.lege.android.db.PlanUserDao;
import com.lege.android.db.RecentlyPlayedUserDao;
import com.lege.android.db.ReminderUserDao;
import com.lege.android.db.ScheduleUserDao;
import com.lege.android.db.TaskBeanDao;
import com.lege.android.db.TipsHistoryBeanDao;
import com.lege.android.db.UserDao;
import com.lege.android.db.WallpaperUserDao;
import com.lege.android.db.WeatherUserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig alarmUserDaoConfig;
    private final DaoConfig articleHistoryBeanDaoConfig;
    private final DaoConfig audioRecordUserDaoConfig;
    private final DaoConfig collectionUserDaoConfig;
    private final DaoConfig emailMessageUserDaoConfig;
    private final DaoConfig emailUserDaoConfig;
    private final DaoConfig globalClockUserDaoConfig;
    private final DaoConfig messageUserDaoConfig;
    private final DaoConfig missedCallRecordUserDaoConfig;
    private final DaoConfig newRemindUserDaoConfig;
    private final DaoConfig newsUserDaoConfig;
    private final DaoConfig noticeUserDaoConfig;
    private final DaoConfig planUserDaoConfig;
    private final DaoConfig recentlyPlayedUserDaoConfig;
    private final DaoConfig reminderUserDaoConfig;
    private final DaoConfig scheduleUserDaoConfig;
    private final DaoConfig taskBeanDaoConfig;
    private final DaoConfig tipsHistoryBeanDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig wallpaperUserDaoConfig;
    private final DaoConfig weatherUserDaoConfig;

    private final AlarmUserDao alarmUserDao;
    private final ArticleHistoryBeanDao articleHistoryBeanDao;
    private final AudioRecordUserDao audioRecordUserDao;
    private final CollectionUserDao collectionUserDao;
    private final EmailMessageUserDao emailMessageUserDao;
    private final EmailUserDao emailUserDao;
    private final GlobalClockUserDao globalClockUserDao;
    private final MessageUserDao messageUserDao;
    private final MissedCallRecordUserDao missedCallRecordUserDao;
    private final NewRemindUserDao newRemindUserDao;
    private final NewsUserDao newsUserDao;
    private final NoticeUserDao noticeUserDao;
    private final PlanUserDao planUserDao;
    private final RecentlyPlayedUserDao recentlyPlayedUserDao;
    private final ReminderUserDao reminderUserDao;
    private final ScheduleUserDao scheduleUserDao;
    private final TaskBeanDao taskBeanDao;
    private final TipsHistoryBeanDao tipsHistoryBeanDao;
    private final UserDao userDao;
    private final WallpaperUserDao wallpaperUserDao;
    private final WeatherUserDao weatherUserDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        alarmUserDaoConfig = daoConfigMap.get(AlarmUserDao.class).clone();
        alarmUserDaoConfig.initIdentityScope(type);

        articleHistoryBeanDaoConfig = daoConfigMap.get(ArticleHistoryBeanDao.class).clone();
        articleHistoryBeanDaoConfig.initIdentityScope(type);

        audioRecordUserDaoConfig = daoConfigMap.get(AudioRecordUserDao.class).clone();
        audioRecordUserDaoConfig.initIdentityScope(type);

        collectionUserDaoConfig = daoConfigMap.get(CollectionUserDao.class).clone();
        collectionUserDaoConfig.initIdentityScope(type);

        emailMessageUserDaoConfig = daoConfigMap.get(EmailMessageUserDao.class).clone();
        emailMessageUserDaoConfig.initIdentityScope(type);

        emailUserDaoConfig = daoConfigMap.get(EmailUserDao.class).clone();
        emailUserDaoConfig.initIdentityScope(type);

        globalClockUserDaoConfig = daoConfigMap.get(GlobalClockUserDao.class).clone();
        globalClockUserDaoConfig.initIdentityScope(type);

        messageUserDaoConfig = daoConfigMap.get(MessageUserDao.class).clone();
        messageUserDaoConfig.initIdentityScope(type);

        missedCallRecordUserDaoConfig = daoConfigMap.get(MissedCallRecordUserDao.class).clone();
        missedCallRecordUserDaoConfig.initIdentityScope(type);

        newRemindUserDaoConfig = daoConfigMap.get(NewRemindUserDao.class).clone();
        newRemindUserDaoConfig.initIdentityScope(type);

        newsUserDaoConfig = daoConfigMap.get(NewsUserDao.class).clone();
        newsUserDaoConfig.initIdentityScope(type);

        noticeUserDaoConfig = daoConfigMap.get(NoticeUserDao.class).clone();
        noticeUserDaoConfig.initIdentityScope(type);

        planUserDaoConfig = daoConfigMap.get(PlanUserDao.class).clone();
        planUserDaoConfig.initIdentityScope(type);

        recentlyPlayedUserDaoConfig = daoConfigMap.get(RecentlyPlayedUserDao.class).clone();
        recentlyPlayedUserDaoConfig.initIdentityScope(type);

        reminderUserDaoConfig = daoConfigMap.get(ReminderUserDao.class).clone();
        reminderUserDaoConfig.initIdentityScope(type);

        scheduleUserDaoConfig = daoConfigMap.get(ScheduleUserDao.class).clone();
        scheduleUserDaoConfig.initIdentityScope(type);

        taskBeanDaoConfig = daoConfigMap.get(TaskBeanDao.class).clone();
        taskBeanDaoConfig.initIdentityScope(type);

        tipsHistoryBeanDaoConfig = daoConfigMap.get(TipsHistoryBeanDao.class).clone();
        tipsHistoryBeanDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        wallpaperUserDaoConfig = daoConfigMap.get(WallpaperUserDao.class).clone();
        wallpaperUserDaoConfig.initIdentityScope(type);

        weatherUserDaoConfig = daoConfigMap.get(WeatherUserDao.class).clone();
        weatherUserDaoConfig.initIdentityScope(type);

        alarmUserDao = new AlarmUserDao(alarmUserDaoConfig, this);
        articleHistoryBeanDao = new ArticleHistoryBeanDao(articleHistoryBeanDaoConfig, this);
        audioRecordUserDao = new AudioRecordUserDao(audioRecordUserDaoConfig, this);
        collectionUserDao = new CollectionUserDao(collectionUserDaoConfig, this);
        emailMessageUserDao = new EmailMessageUserDao(emailMessageUserDaoConfig, this);
        emailUserDao = new EmailUserDao(emailUserDaoConfig, this);
        globalClockUserDao = new GlobalClockUserDao(globalClockUserDaoConfig, this);
        messageUserDao = new MessageUserDao(messageUserDaoConfig, this);
        missedCallRecordUserDao = new MissedCallRecordUserDao(missedCallRecordUserDaoConfig, this);
        newRemindUserDao = new NewRemindUserDao(newRemindUserDaoConfig, this);
        newsUserDao = new NewsUserDao(newsUserDaoConfig, this);
        noticeUserDao = new NoticeUserDao(noticeUserDaoConfig, this);
        planUserDao = new PlanUserDao(planUserDaoConfig, this);
        recentlyPlayedUserDao = new RecentlyPlayedUserDao(recentlyPlayedUserDaoConfig, this);
        reminderUserDao = new ReminderUserDao(reminderUserDaoConfig, this);
        scheduleUserDao = new ScheduleUserDao(scheduleUserDaoConfig, this);
        taskBeanDao = new TaskBeanDao(taskBeanDaoConfig, this);
        tipsHistoryBeanDao = new TipsHistoryBeanDao(tipsHistoryBeanDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);
        wallpaperUserDao = new WallpaperUserDao(wallpaperUserDaoConfig, this);
        weatherUserDao = new WeatherUserDao(weatherUserDaoConfig, this);

        registerDao(AlarmUser.class, alarmUserDao);
        registerDao(ArticleHistoryBean.class, articleHistoryBeanDao);
        registerDao(AudioRecordUser.class, audioRecordUserDao);
        registerDao(CollectionUser.class, collectionUserDao);
        registerDao(EmailMessageUser.class, emailMessageUserDao);
        registerDao(EmailUser.class, emailUserDao);
        registerDao(GlobalClockUser.class, globalClockUserDao);
        registerDao(MessageUser.class, messageUserDao);
        registerDao(MissedCallRecordUser.class, missedCallRecordUserDao);
        registerDao(NewRemindUser.class, newRemindUserDao);
        registerDao(NewsUser.class, newsUserDao);
        registerDao(NoticeUser.class, noticeUserDao);
        registerDao(PlanUser.class, planUserDao);
        registerDao(RecentlyPlayedUser.class, recentlyPlayedUserDao);
        registerDao(ReminderUser.class, reminderUserDao);
        registerDao(ScheduleUser.class, scheduleUserDao);
        registerDao(TaskBean.class, taskBeanDao);
        registerDao(TipsHistoryBean.class, tipsHistoryBeanDao);
        registerDao(User.class, userDao);
        registerDao(WallpaperUser.class, wallpaperUserDao);
        registerDao(WeatherUser.class, weatherUserDao);
    }
    
    public void clear() {
        alarmUserDaoConfig.getIdentityScope().clear();
        articleHistoryBeanDaoConfig.getIdentityScope().clear();
        audioRecordUserDaoConfig.getIdentityScope().clear();
        collectionUserDaoConfig.getIdentityScope().clear();
        emailMessageUserDaoConfig.getIdentityScope().clear();
        emailUserDaoConfig.getIdentityScope().clear();
        globalClockUserDaoConfig.getIdentityScope().clear();
        messageUserDaoConfig.getIdentityScope().clear();
        missedCallRecordUserDaoConfig.getIdentityScope().clear();
        newRemindUserDaoConfig.getIdentityScope().clear();
        newsUserDaoConfig.getIdentityScope().clear();
        noticeUserDaoConfig.getIdentityScope().clear();
        planUserDaoConfig.getIdentityScope().clear();
        recentlyPlayedUserDaoConfig.getIdentityScope().clear();
        reminderUserDaoConfig.getIdentityScope().clear();
        scheduleUserDaoConfig.getIdentityScope().clear();
        taskBeanDaoConfig.getIdentityScope().clear();
        tipsHistoryBeanDaoConfig.getIdentityScope().clear();
        userDaoConfig.getIdentityScope().clear();
        wallpaperUserDaoConfig.getIdentityScope().clear();
        weatherUserDaoConfig.getIdentityScope().clear();
    }

    public AlarmUserDao getAlarmUserDao() {
        return alarmUserDao;
    }

    public ArticleHistoryBeanDao getArticleHistoryBeanDao() {
        return articleHistoryBeanDao;
    }

    public AudioRecordUserDao getAudioRecordUserDao() {
        return audioRecordUserDao;
    }

    public CollectionUserDao getCollectionUserDao() {
        return collectionUserDao;
    }

    public EmailMessageUserDao getEmailMessageUserDao() {
        return emailMessageUserDao;
    }

    public EmailUserDao getEmailUserDao() {
        return emailUserDao;
    }

    public GlobalClockUserDao getGlobalClockUserDao() {
        return globalClockUserDao;
    }

    public MessageUserDao getMessageUserDao() {
        return messageUserDao;
    }

    public MissedCallRecordUserDao getMissedCallRecordUserDao() {
        return missedCallRecordUserDao;
    }

    public NewRemindUserDao getNewRemindUserDao() {
        return newRemindUserDao;
    }

    public NewsUserDao getNewsUserDao() {
        return newsUserDao;
    }

    public NoticeUserDao getNoticeUserDao() {
        return noticeUserDao;
    }

    public PlanUserDao getPlanUserDao() {
        return planUserDao;
    }

    public RecentlyPlayedUserDao getRecentlyPlayedUserDao() {
        return recentlyPlayedUserDao;
    }

    public ReminderUserDao getReminderUserDao() {
        return reminderUserDao;
    }

    public ScheduleUserDao getScheduleUserDao() {
        return scheduleUserDao;
    }

    public TaskBeanDao getTaskBeanDao() {
        return taskBeanDao;
    }

    public TipsHistoryBeanDao getTipsHistoryBeanDao() {
        return tipsHistoryBeanDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public WallpaperUserDao getWallpaperUserDao() {
        return wallpaperUserDao;
    }

    public WeatherUserDao getWeatherUserDao() {
        return weatherUserDao;
    }

}
