package com.lege.android.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.lege.android.base.db.User;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "USER".
*/
public class UserDao extends AbstractDao<User, Long> {

    public static final String TABLENAME = "USER";

    /**
     * Properties of entity User.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Uid = new Property(1, String.class, "uid", false, "UID");
        public final static Property Name = new Property(2, String.class, "name", false, "NAME");
        public final static Property Date = new Property(3, String.class, "date", false, "DATE");
        public final static Property State = new Property(4, String.class, "state", false, "STATE");
        public final static Property Position = new Property(5, String.class, "position", false, "POSITION");
        public final static Property Dept = new Property(6, String.class, "dept", false, "DEPT");
        public final static Property Collection = new Property(7, String.class, "collection", false, "COLLECTION");
        public final static Property Huanxin = new Property(8, String.class, "huanxin", false, "HUANXIN");
        public final static Property Readed = new Property(9, String.class, "readed", false, "READED");
    };


    public UserDao(DaoConfig config) {
        super(config);
    }
    
    public UserDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"USER\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"UID\" TEXT," + // 1: uid
                "\"NAME\" TEXT," + // 2: name
                "\"DATE\" TEXT," + // 3: date
                "\"STATE\" TEXT," + // 4: state
                "\"POSITION\" TEXT," + // 5: position
                "\"DEPT\" TEXT," + // 6: dept
                "\"COLLECTION\" TEXT," + // 7: collection
                "\"HUANXIN\" TEXT," + // 8: huanxin
                "\"READED\" TEXT);"); // 9: readed
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"USER\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, User entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String uid = entity.getUid();
        if (uid != null) {
            stmt.bindString(2, uid);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        String date = entity.getDate();
        if (date != null) {
            stmt.bindString(4, date);
        }
 
        String state = entity.getState();
        if (state != null) {
            stmt.bindString(5, state);
        }
 
        String position = entity.getPosition();
        if (position != null) {
            stmt.bindString(6, position);
        }
 
        String dept = entity.getDept();
        if (dept != null) {
            stmt.bindString(7, dept);
        }
 
        String collection = entity.getCollection();
        if (collection != null) {
            stmt.bindString(8, collection);
        }
 
        String huanxin = entity.getHuanxin();
        if (huanxin != null) {
            stmt.bindString(9, huanxin);
        }
 
        String readed = entity.getReaded();
        if (readed != null) {
            stmt.bindString(10, readed);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, User entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String uid = entity.getUid();
        if (uid != null) {
            stmt.bindString(2, uid);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        String date = entity.getDate();
        if (date != null) {
            stmt.bindString(4, date);
        }
 
        String state = entity.getState();
        if (state != null) {
            stmt.bindString(5, state);
        }
 
        String position = entity.getPosition();
        if (position != null) {
            stmt.bindString(6, position);
        }
 
        String dept = entity.getDept();
        if (dept != null) {
            stmt.bindString(7, dept);
        }
 
        String collection = entity.getCollection();
        if (collection != null) {
            stmt.bindString(8, collection);
        }
 
        String huanxin = entity.getHuanxin();
        if (huanxin != null) {
            stmt.bindString(9, huanxin);
        }
 
        String readed = entity.getReaded();
        if (readed != null) {
            stmt.bindString(10, readed);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public User readEntity(Cursor cursor, int offset) {
        User entity = new User( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // uid
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // name
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // date
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // state
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // position
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // dept
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // collection
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // huanxin
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9) // readed
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, User entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUid(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setDate(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setState(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setPosition(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setDept(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setCollection(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setHuanxin(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setReaded(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(User entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(User entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
